services:

  mariadb:
    build: ./.docker/mariadb
    image: ${PROJECT_NAME}-mariadb
    container_name: ${PROJECT_NAME}-mariadb
    env_file:
      - ./.env
    ports:
      - ${_MARIADB_HOST_PORT}:3306
    volumes:
      - ./.docker/.mariadb:/var/lib/mysql
    working_dir: /app
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  wordpress:
    build: ./.docker/wordpress
    image: ${PROJECT_NAME}-wordpress
    container_name: ${PROJECT_NAME}-wordpress
    env_file:
      - ./.env
    ports:
      - ${_WORDPRESS_HOST_PORT}:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always

networks:
  default:
    name: ${PROJECT_NAME}-default
